Feature Engineering

# Standard_Scaler

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


data = {
    'age': np.random.randint(20, 60, 7),
    'income': np.random.randint(30000, 100000, 7)
}
df = pd.DataFrame(data)

display(df)

x = df[["age","income"]]

x_train , x_test = train_test_split(x , test_size = 0.2 , random_state = 42)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

,age,income
0,51,74121
1,34,88948
2,55,48953
3,38,50285
4,34,50438
5,20,51520
6,54,67968


In [6]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

df = pd.DataFrame({
    "city": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai"],
    "education": ["Bachelors", "Masters", "PhD", "Bachelors", "Masters"],
    "target": [1, 0, 1, 0, 1]
})

le = LabelEncoder()
df["city_label"] = le.fit_transform(df["city"])

df_ohe = pd.get_dummies(df, columns=["city"], prefix="city")


ohe = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
city_ohe = ohe.fit_transform(df[["city"]])


edu_order = [["Bachelors", "Masters", "PhD"]]
ord_enc = OrdinalEncoder(categories=edu_order)
df["education_ordinal"] = ord_enc.fit_transform(df[["education"]])

print(df)
print(df_ohe)
print(city_ohe)

      city  education  target  city_label  education_ordinal
0    Delhi  Bachelors       1           1                0.0
1   Mumbai    Masters       0           2                1.0
2    Delhi        PhD       1           1                2.0
3  Chennai  Bachelors       0           0                0.0
4   Mumbai    Masters       1           2                1.0
   education  target  city_label  city_Chennai  city_Delhi  city_Mumbai
0  Bachelors       1           1         False        True        False
1    Masters       0           2         False       False         True
2        PhD       1           1         False        True        False
3  Bachelors       0           0          True       False        False
4    Masters       1           2         False       False         True
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


# Lable & Ordinals


In [9]:
le = LabelEncoder() 
df["education_label"] = le.fit_transform(df["education"])
df

,city,education,target,city_label,education_ordinal,education_label
0,Delhi,Bachelors,1,1,0.0,0
1,Mumbai,Masters,0,2,1.0,1
2,Delhi,PhD,1,1,2.0,2
3,Chennai,Bachelors,0,0,0.0,0
4,Mumbai,Masters,1,2,1.0,1


In [8]:
le = LabelEncoder()
df["city_label"] = le.fit_transform(df["city"])
df


,city,education,target,city_label,education_ordinal
0,Delhi,Bachelors,1,1,0.0
1,Mumbai,Masters,0,2,1.0
2,Delhi,PhD,1,1,2.0
3,Chennai,Bachelors,0,0,0.0
4,Mumbai,Masters,1,2,1.0


In [11]:
edu_order = [["Bachelors", "Masters", "PhD"]]
ord_enc = OrdinalEncoder(categories=edu_order) 
df["education_ordinal"] = ord_enc.fit_transform(df[["education"]])
df 

,city,education,target,city_label,education_ordinal,education_label
0,Delhi,Bachelors,1,1,0.0,0
1,Mumbai,Masters,0,2,1.0,1
2,Delhi,PhD,1,1,2.0,2
3,Chennai,Bachelors,0,0,0.0,0
4,Mumbai,Masters,1,2,1.0,1


one hot encoding

In [ ]:
df_ohe = pd.get_dummies(df, columns=["city"], prefix="city")
df_ohe

# true ki value 1 and false ki value 0


,education,target,city_label,education_ordinal,education_label,city_Chennai,city_Delhi,city_Mumbai
0,Bachelors,1,1,0.0,0,False,True,False
1,Masters,0,2,1.0,1,False,False,True
2,PhD,1,1,2.0,2,False,True,False
3,Bachelors,0,0,0.0,0,True,False,False
4,Masters,1,2,1.0,1,False,False,True


In [ ]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
city_ohe = ohe.fit_transform(df[["city"]])





,city,education,target,city_label,education_ordinal,education_label
0,Delhi,Bachelors,1,1,0.0,0
1,Mumbai,Masters,0,2,1.0,1
2,Delhi,PhD,1,1,2.0,2
3,Chennai,Bachelors,0,0,0.0,0
4,Mumbai,Masters,1,2,1.0,1


# from Scipy.stats import skew

In [5]:
from scipy import stats
import scipy
import pandas as pd

date = pd.DataFrame({
    "age": [25, 30, 35, 40, 100],   
    "income": [50000, 60000, 70000, 80000, 900000]
})
print(scipy.stats.skew(date["age"]))
print(scipy.stats.skew(date["income"]))
date




1.377116441994151
1.4966425232061928


,age,income
0,25,50000
1,30,60000
2,35,70000
3,40,80000
4,100,900000
